### ISSUE TITLE
Using importHelpers: true but not depending on tslib

### ISSUE THREAD

**Issue by pluma** [Saifadin/postonents#4]
The project compiles TS to ES5 with `importHelpers: true` in `tsconfig.base.json`. This results in the compiled code containing imports from `tslib`, which is not an explicit production dependency.

This currently means the npm release can not be used without adding `tslib` as a manual dependency.

I would recommend either disabling this option (only really serves to reduce file size) or explicitly adding `tslib` to the dependencies. Personally I'd prefer just setting the option to `false`.

**Comment by Saifadin** [comment]
Thanks a lot for the hint, I was not aware of that 🤔
I will change that tonight, good catch 🙌🏽

Or if you want you can add a PR ^^

**Comment by Saifadin** [comment]
I resolved it, thank you ^^
